spring:
  datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/bs
        username: root
        password: *******
        driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    check-template: true
    mode: HTML5
    suffix: .html
    prefix: classpath:/templates/
    encoding: UTF-8

#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .jsp ï¼Œ.html
server:
  port: 80
